services:
  meilisearch:
    image: getmeili/meilisearch:v1.12
    ports:
      - 7700:7700
    volumes:
      - meili-data:/meili_data
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_MASTER_KEY}

volumes:
  meili-data:
